# Generated by Django 4.2.9 on 2026-07-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_by_user_external_id_user_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Chefe DTI)'), ('tecnico', 'Técnico'), ('docente', 'Docente'), ('secretario', 'Secretário'), ('coordenador', 'Coordenador')], default='tecnico', max_length=20, verbose_name='Função'),
        ),
        migrations.CreateModel(
            name='AtribuidorEventual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('morada', models.TextField(verbose_name='Morada')),
                ('grau_academico', models.CharField(max_length=255, verbose_name='Grau Académico')),
                ('entidade_empregadora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidade Empregadora (opcional)')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('funcao', models.CharField(choices=[('formador', 'Formador'), ('palestrante', 'Palestrante'), ('monitor', 'Monitor'), ('mentor', 'Mentor'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Função')),
                ('funcao_outro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outra função (especifique)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuidores_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (admin)')),
            ],
            options={
                'verbose_name': 'Atribuidor Eventual',
                'verbose_name_plural': 'Atribuidores Eventuais',
                'db_table': 'atribuidores_eventuais',
            },
        ),
    ]
