# Generated by Django 4.2.9 on 2025-07-28 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('type', models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('projetor', 'Projetor'), ('impressora', 'Impressora'), ('monitor', 'Monitor'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('reservado', 'Reservado'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Aquisição')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'equipment',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
