# Generated by Django 4.2.9 on 2025-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, help_text='Categoria adicional do equipamento (ex: Profissional, Educacional, etc.)', max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor'),
        ),
    ]
