# Generated by Django 4.2.9 on 2025-11-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0002_equipment_category_equipment_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Pacote')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_template', models.BooleanField(default=True, help_text='Se verdadeiro, este pacote pode ser usado como base para novos pacotes', verbose_name='É Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pacote de Equipamentos',
                'verbose_name_plural': 'Pacotes de Equipamentos',
                'db_table': 'equipment_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('is_optional', models.BooleanField(default=False, help_text='Se verdadeiro, este item pode ser removido do pacote', verbose_name='Opcional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='equipment.equipment', verbose_name='Equipamento')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.equipmentpackage', verbose_name='Pacote')),
            ],
            options={
                'verbose_name': 'Item do Pacote',
                'verbose_name_plural': 'Itens do Pacote',
                'db_table': 'package_items',
                'unique_together': {('package', 'equipment')},
            },
        ),
    ]
