# Generated by Django 4.2.9 on 2026-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentpackage_packageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='qrcode_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash do QR Code'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('projetor', 'Projetor'), ('impressora', 'Impressora'), ('monitor', 'Monitor'), ('acessorio', 'Acessório'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
    ]
