# Generated by Django 4.2.9 on 2025-08-08 10:11

from django.db import migrations, models
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=reservations.models.get_current_date, verbose_name='Data da Reserva'),
        ),
    ]
