# Generated by Django 4.2.9 on 2025-07-28 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('expected_return_date', models.DateField(verbose_name='Data Prevista de Devolução')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Data Real de Devolução')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status')),
                ('purpose', models.TextField(verbose_name='Finalidade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='equipment.equipment', verbose_name='Equipamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
