# Generated by Django 4.2.9 on 2025-08-08 10:11

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=loans.models.get_current_date, verbose_name='Data de Início'),
        ),
    ]
