# Generated by Django 4.2.9 on 2025-08-15 14:36

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='start_time',
            field=models.TimeField(default=loans.models.get_current_time, verbose_name='Hora de Início'),
        ),
    ]
