# Generated by Django 4.2.9 on 2025-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='expected_return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Prevista de Devolução'),
        ),
    ]
