# Generated by Django 4.2.9 on 2025-10-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0004_loan_expected_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='confirmado_levantamento',
            field=models.BooleanField(default=False, verbose_name='Levantamento confirmado'),
        ),
        migrations.AddField(
            model_name='loan',
            name='data_confirmacao_levantamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de confirmação do levantamento'),
        ),
        migrations.AddField(
            model_name='loan',
            name='tecnico_entrega',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Técnico que entregou'),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantidade de equipamentos')),
                ('purpose', models.TextField(verbose_name='Finalidade')),
                ('expected_return_date', models.DateField(verbose_name='Data Prevista de Devolução')),
                ('expected_return_time', models.TimeField(blank=True, null=True, verbose_name='Hora Prevista de Devolução')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('motivo_decisao', models.TextField(blank=True, null=True, verbose_name='Motivo da aprovação/rejeição')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da decisão')),
                ('data_levantamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de levantamento')),
                ('confirmado_pelo_tecnico', models.BooleanField(default=False, verbose_name='Levantamento confirmado pelo técnico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/Rejeitado por')),
                ('equipments', models.ManyToManyField(related_name='loan_requests', to='equipment.equipment', verbose_name='Equipamentos solicitados')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, limit_choices_to={'role': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Solicitação de Empréstimo',
                'verbose_name_plural': 'Solicitações de Empréstimos',
                'db_table': 'loan_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
