# Generated by Django 4.2.9 on 2025-10-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('loans', '0005_loan_confirmado_levantamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente Levantamento'), ('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='LoanEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='É o equipamento principal')),
                ('returned', models.BooleanField(default=False, verbose_name='Devolvido')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de devolução')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_items', to='equipment.equipment', verbose_name='Equipamento')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_equipments', to='loans.loan', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Equipamento do Empréstimo',
                'verbose_name_plural': 'Equipamentos dos Empréstimos',
                'db_table': 'loan_equipments',
                'unique_together': {('loan', 'equipment')},
            },
        ),
    ]
