# Generated by Django 4.2.9 on 2026-07-02 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentpackage_packageitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0006_alter_loan_status_loanequipment'),
    ]

    operations = [
        # Add new fields (keep old ones for data migration)
        migrations.AddField(
            model_name='loan',
            name='confirmado_tecnico',
            field=models.BooleanField(default=False, verbose_name='Confirmado pelo técnico'),
        ),
        migrations.AddField(
            model_name='loan',
            name='confirmado_utente',
            field=models.BooleanField(default=False, verbose_name='Confirmado pelo utente'),
        ),
        migrations.AddField(
            model_name='loan',
            name='data_confirmacao_tecnico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de confirmação do técnico'),
        ),
        migrations.AddField(
            model_name='loan',
            name='data_confirmacao_utente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de confirmação do utente'),
        ),
        migrations.AddField(
            model_name='loan',
            name='devolucao_mesmo_dia',
            field=models.BooleanField(default=False, verbose_name='Devolução no mesmo dia?'),
        ),
        migrations.AddField(
            model_name='loan',
            name='dias_previstos_devolucao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias previstos para devolução'),
        ),
        migrations.AddField(
            model_name='loan',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='equipment.equipmentpackage', verbose_name='Pacote'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='confirmado_pelo_utente',
            field=models.BooleanField(default=False, verbose_name='Confirmado pelo utente'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de cancelamento'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='data_confirmacao_utente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de confirmação do utente'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='devolucao_mesmo_dia',
            field=models.BooleanField(default=False, verbose_name='Devolução no mesmo dia?'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='dias_previstos_devolucao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias previstos para devolução'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests', to='equipment.equipmentpackage', verbose_name='Pacote'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='equipment.equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='confirmado_pelo_tecnico',
            field=models.BooleanField(default=False, verbose_name='Confirmado pelo técnico'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
