# Generated by Django 4.2.9 on 2026-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_migrate_loan_confirmations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='confirmado_levantamento',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='data_confirmacao_levantamento',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='dias_previstos_devolucao',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='dias_previstos_devolucao',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='loan',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista de devolução'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista de devolução'),
        ),
    ]
