# Generated by Django 4.2.9 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_rename_dias_to_data_prevista_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de equipamentos'),
        ),
    ]
