# Generated by Django 4.2.9 on 2026-07-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_add_quantity_to_loanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='qrcode_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash do QR Code'),
        ),
    ]
