# Generated by Django 4.2.9 on 2026-08-18 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0011_add_qrcode_to_loanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='documento_anexado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do anexo do documento'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='documento_anexado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Documento anexado por'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='documento_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome original do documento'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='documento_validado',
            field=models.FileField(blank=True, null=True, upload_to='solicitacoes/documentos/%Y/%m/', verbose_name='Documento validado pela Reitoria'),
        ),
    ]
