# Generated by Django 4.2.9 on 2026-08-18 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0012_loanrequest_documento_anexado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='documento_devolucao',
            field=models.FileField(blank=True, null=True, upload_to='devolucoes/%Y/%m/', verbose_name='Imagem ou relatório da devolução'),
        ),
        migrations.AddField(
            model_name='loan',
            name='estado_devolucao',
            field=models.CharField(blank=True, choices=[('disponivel', 'Bom estado - disponível'), ('manutencao', 'Necessita manutenção'), ('danificado', 'Danificado - indisponível')], max_length=20, null=True, verbose_name='Estado físico na devolução'),
        ),
        migrations.AddField(
            model_name='loan',
            name='observacoes_devolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da devolução'),
        ),
        migrations.AddField(
            model_name='loan',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico que recebeu a devolução'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='comprovativo_levantamento',
            field=models.FileField(blank=True, null=True, upload_to='solicitacoes/comprovativos/%Y/%m/', verbose_name='Comprovativo digital de levantamento'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Em análise'), ('autorizado', 'Em levantamento'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
